
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lucas
 */
public class PaginaIniciar extends javax.swing.JFrame {

    /**
     * Creates new form PaginaIniciar
     */
    public PaginaIniciar() {
        initComponents();
    }

    public void MontarComputador() {
        double valorTotal = 0;
        String valorTotalFormatado;
        DecimalFormat formato = new DecimalFormat("R$ #,##0.00");

        if (IntelCorei3RadioButton.isSelected()) {
            valorTotal += 275;
        }
        if (AMDAthlonIIRadioButton.isSelected()) {
            valorTotal += 125;
        }
        if (SATA500GBRadioButton.isSelected()) {
            valorTotal += 300;
        }
        if (IDE320GBRadioButton.isSelected()) {
            valorTotal += 230;
        }
        if (Memoria4GBRadioButton.isSelected()) {
            valorTotal += 250;
        }
        if (Memoria3GBRadioButton.isSelected()) {
            valorTotal += 200;
        }
        if (LCD15RadioButton.isSelected()) {
            valorTotal += 350;
        }
        if (LCD17RadioButton.isSelected()) {
            valorTotal += 450;
        }
        if (Windows7HomeRadioButton.isSelected()) {
            valorTotal += 330;
        }
        if (LinuxRadioButton.isSelected()) {
            valorTotal += 0;
        }

        valorTotalFormatado = formato.format(valorTotal);
        ValorTotalLabel.setText(valorTotalFormatado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcessadorbuttonGroup = new javax.swing.ButtonGroup();
        DiscoRigidobuttonGroup = new javax.swing.ButtonGroup();
        MemoriabuttonGroup = new javax.swing.ButtonGroup();
        MonitorbuttonGroup = new javax.swing.ButtonGroup();
        SistOperacionalbuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        IntelCorei3RadioButton = new javax.swing.JRadioButton();
        AMDAthlonIIRadioButton = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        SATA500GBRadioButton = new javax.swing.JRadioButton();
        IDE320GBRadioButton = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Memoria4GBRadioButton = new javax.swing.JRadioButton();
        Memoria3GBRadioButton = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        LCD17RadioButton = new javax.swing.JRadioButton();
        LCD15RadioButton = new javax.swing.JRadioButton();
        jSeparator5 = new javax.swing.JSeparator();
        Windows7HomeRadioButton = new javax.swing.JRadioButton();
        LinuxRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Loja de Informatica");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loja de informatica LFC");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Monte seu computador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 1, 12)); // NOI18N
        jLabel2.setText("Itens:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Prestige Elite Std", 1, 12)); // NOI18N
        jLabel4.setText("Modelo 1 (Preço)");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Prestige Elite Std", 1, 12)); // NOI18N
        jLabel5.setText("Modelo 2 (Preço)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/01_processador-mobile-intel-celeron-t3300-2-00-1m-800-slgjw_peq.jpg"))); // NOI18N
        jLabel3.setText("Processador:");

        IntelCorei3RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        ProcessadorbuttonGroup.add(IntelCorei3RadioButton);
        IntelCorei3RadioButton.setSelected(true);
        IntelCorei3RadioButton.setText("Intel Core i3 – R$ 275,00");
        IntelCorei3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntelCorei3RadioButtonActionPerformed(evt);
            }
        });

        AMDAthlonIIRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        ProcessadorbuttonGroup.add(AMDAthlonIIRadioButton);
        AMDAthlonIIRadioButton.setText("AMD Athlon II – R$ 125,00");
        AMDAthlonIIRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMDAthlonIIRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/images.jpg"))); // NOI18N
        jLabel6.setText("Disco rígido :");

        SATA500GBRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DiscoRigidobuttonGroup.add(SATA500GBRadioButton);
        SATA500GBRadioButton.setSelected(true);
        SATA500GBRadioButton.setText("SATA 500 GB – R$ 300,00");
        SATA500GBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SATA500GBRadioButtonActionPerformed(evt);
            }
        });

        IDE320GBRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        DiscoRigidobuttonGroup.add(IDE320GBRadioButton);
        IDE320GBRadioButton.setText("IDE 320GB – R$ 230,00");
        IDE320GBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDE320GBRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Memória.jpg"))); // NOI18N
        jLabel7.setText("Memória :");

        Memoria4GBRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        MemoriabuttonGroup.add(Memoria4GBRadioButton);
        Memoria4GBRadioButton.setSelected(true);
        Memoria4GBRadioButton.setText("4GB – R$ 250,00");
        Memoria4GBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Memoria4GBRadioButtonActionPerformed(evt);
            }
        });

        Memoria3GBRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        MemoriabuttonGroup.add(Memoria3GBRadioButton);
        Memoria3GBRadioButton.setText("3GB – R$ 200,00");
        Memoria3GBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Memoria3GBRadioButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/monitor-lcd-19-samsung-widescreen-931bw-photo6100655-5-20-31.jpg"))); // NOI18N
        jLabel8.setText("Monitor :");

        LCD17RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        MonitorbuttonGroup.add(LCD17RadioButton);
        LCD17RadioButton.setSelected(true);
        LCD17RadioButton.setText("LCD 17” - R$ 450,00");
        LCD17RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCD17RadioButtonActionPerformed(evt);
            }
        });

        LCD15RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        MonitorbuttonGroup.add(LCD15RadioButton);
        LCD15RadioButton.setText("LCD 15” - R$ 350,00");
        LCD15RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCD15RadioButtonActionPerformed(evt);
            }
        });

        Windows7HomeRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        SistOperacionalbuttonGroup.add(Windows7HomeRadioButton);
        Windows7HomeRadioButton.setSelected(true);
        Windows7HomeRadioButton.setText("Win7 Home Premium – R$ 330,00");
        Windows7HomeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Windows7HomeRadioButtonActionPerformed(evt);
            }
        });

        LinuxRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        SistOperacionalbuttonGroup.add(LinuxRadioButton);
        LinuxRadioButton.setText("Linux – R$ 0,00");
        LinuxRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinuxRadioButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/03_sistema-operacional-xp+vista+seven+chave-ativacao-definitiva_peq.jpg"))); // NOI18N
        jLabel9.setText("<html>Sistema<br/> Operacional </html>");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Valor Total:");

        ValorTotalLabel.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        ValorTotalLabel.setText("R$ 1.605,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(IntelCorei3RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(AMDAthlonIIRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(SATA500GBRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(IDE320GBRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addComponent(Memoria4GBRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53)
                                .addComponent(Memoria3GBRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(LCD17RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(LCD15RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(48, 48, 48)
                        .addComponent(Windows7HomeRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LinuxRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValorTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IntelCorei3RadioButton)
                    .addComponent(AMDAthlonIIRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SATA500GBRadioButton)
                    .addComponent(IDE320GBRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Memoria4GBRadioButton)
                    .addComponent(Memoria3GBRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LCD17RadioButton)
                    .addComponent(LCD15RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Windows7HomeRadioButton)
                            .addComponent(LinuxRadioButton))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ValorTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/btSair.gif"))); // NOI18N
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LCD15RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCD15RadioButtonActionPerformed
        MontarComputador();
    }//GEN-LAST:event_LCD15RadioButtonActionPerformed

    private void LinuxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinuxRadioButtonActionPerformed
        MontarComputador();
    }//GEN-LAST:event_LinuxRadioButtonActionPerformed

    private void IntelCorei3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntelCorei3RadioButtonActionPerformed
        MontarComputador();
    }//GEN-LAST:event_IntelCorei3RadioButtonActionPerformed

    private void AMDAthlonIIRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMDAthlonIIRadioButtonActionPerformed
        MontarComputador();        
    }//GEN-LAST:event_AMDAthlonIIRadioButtonActionPerformed

    private void SATA500GBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SATA500GBRadioButtonActionPerformed
        MontarComputador();        
    }//GEN-LAST:event_SATA500GBRadioButtonActionPerformed

    private void IDE320GBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDE320GBRadioButtonActionPerformed
        MontarComputador();        
    }//GEN-LAST:event_IDE320GBRadioButtonActionPerformed

    private void Memoria4GBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Memoria4GBRadioButtonActionPerformed
        MontarComputador();       
    }//GEN-LAST:event_Memoria4GBRadioButtonActionPerformed

    private void Memoria3GBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Memoria3GBRadioButtonActionPerformed
        MontarComputador();       
    }//GEN-LAST:event_Memoria3GBRadioButtonActionPerformed

    private void LCD17RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCD17RadioButtonActionPerformed
        MontarComputador();       
    }//GEN-LAST:event_LCD17RadioButtonActionPerformed

    private void Windows7HomeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Windows7HomeRadioButtonActionPerformed
        MontarComputador();        
    }//GEN-LAST:event_Windows7HomeRadioButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Deseja sair", "Sair", JOptionPane.YES_NO_OPTION)==0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaIniciar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AMDAthlonIIRadioButton;
    private javax.swing.ButtonGroup DiscoRigidobuttonGroup;
    private javax.swing.JRadioButton IDE320GBRadioButton;
    private javax.swing.JRadioButton IntelCorei3RadioButton;
    private javax.swing.JRadioButton LCD15RadioButton;
    private javax.swing.JRadioButton LCD17RadioButton;
    private javax.swing.JRadioButton LinuxRadioButton;
    private javax.swing.JRadioButton Memoria3GBRadioButton;
    private javax.swing.JRadioButton Memoria4GBRadioButton;
    private javax.swing.ButtonGroup MemoriabuttonGroup;
    private javax.swing.ButtonGroup MonitorbuttonGroup;
    private javax.swing.ButtonGroup ProcessadorbuttonGroup;
    private javax.swing.JRadioButton SATA500GBRadioButton;
    private javax.swing.ButtonGroup SistOperacionalbuttonGroup;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.JRadioButton Windows7HomeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
