  /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package revisaocaixa;

import java.awt.CardLayout;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author INFO01
 */
public class Terminal extends javax.swing.JFrame {
    private JTable jTable2;

    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("caixa?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        usuarioQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Usuario u");
        usuarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usuarioQuery.getResultList();
        movimentoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Movimento m");
        movimentoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : movimentoQuery.getResultList();
        Principal = new javax.swing.JPanel();
        Login1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNumeroConta = new javax.swing.JTextField();
        jButtonAcessarConta = new javax.swing.JButton();
        jButtonCancelarConta = new javax.swing.JButton();
        jPasswordFieldSenhaConta = new javax.swing.JPasswordField();
        Saldo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        Extrato = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFielddatainicial = new javax.swing.JTextField();
        jTextFielddatafinal = new javax.swing.JTextField();
        jTextFieldsaldoextrato = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Lancamento = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldHistorico = new javax.swing.JTextField();
        jTextFieldCredito = new javax.swing.JTextField();
        jTextFieldDebito = new javax.swing.JTextField();
        jButtonNovoLancamento = new javax.swing.JButton();
        jButtonSalvarLancamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jButtonUsuario = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jButtonExtrato = new javax.swing.JButton();
        jButtonLancamento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelContaCorrente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        Principal.setBackground(new java.awt.Color(255, 204, 204));
        Principal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Principal.setLayout(new java.awt.CardLayout());

        Login1.setBackground(new java.awt.Color(204, 255, 204));
        Login1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 2, true));

        jLabel9.setText("Numero Conta:");

        jLabel10.setText("Senha:");

        jButtonAcessarConta.setText("Acessar ");
        jButtonAcessarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarContaActionPerformed(evt);
            }
        });

        jButtonCancelarConta.setText("Cancelar");

        javax.swing.GroupLayout Login1Layout = new javax.swing.GroupLayout(Login1);
        Login1.setLayout(Login1Layout);
        Login1Layout.setHorizontalGroup(
            Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login1Layout.createSequentialGroup()
                .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldSenhaConta, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumeroConta)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAcessarConta)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonCancelarConta)))
                .addContainerGap(696, Short.MAX_VALUE))
        );
        Login1Layout.setVerticalGroup(
            Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordFieldSenhaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(Login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAcessarConta)
                    .addComponent(jButtonCancelarConta))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        Principal.add(Login1, "Login1");

        Saldo.setBackground(new java.awt.Color(204, 255, 255));
        Saldo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));

        jLabel4.setText("Saldo Atual:");

        jTextFieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaldoLayout = new javax.swing.GroupLayout(Saldo);
        Saldo.setLayout(SaldoLayout);
        SaldoLayout.setHorizontalGroup(
            SaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaldoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        SaldoLayout.setVerticalGroup(
            SaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaldoLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(SaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        Principal.add(Saldo, "Saldo");

        Extrato.setBackground(new java.awt.Color(255, 204, 204));
        Extrato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));

        jLabel6.setText("Data Inicial:");

        jLabel7.setText("Data Final:");

        jLabel8.setText("Saldo de extrato:");

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, movimentoList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lanc}"));
        columnBinding.setColumnName("Lanc");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${credito}"));
        columnBinding.setColumnName("Credito");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${debito}"));
        columnBinding.setColumnName("Debito");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${historico}"));
        columnBinding.setColumnName("Historico");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
        columnBinding.setColumnName("Saldo");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuario}"));
        columnBinding.setColumnName("Usuario");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ExtratoLayout = new javax.swing.GroupLayout(Extrato);
        Extrato.setLayout(ExtratoLayout);
        ExtratoLayout.setHorizontalGroup(
            ExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExtratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ExtratoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddatainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFielddatafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldsaldoextrato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jButton4))
                    .addGroup(ExtratoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        ExtratoLayout.setVerticalGroup(
            ExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jTextFielddatainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddatafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsaldoextrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(ExtratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Principal.add(Extrato, "Extrato");

        Lancamento.setBackground(new java.awt.Color(204, 204, 255));
        Lancamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel11.setText("Data:");

        jLabel12.setText("Histórico:");

        jLabel13.setText("Crédito:");

        jLabel14.setText("Débito:");

        jButtonNovoLancamento.setText("Novo ");
        jButtonNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoLancamentoActionPerformed(evt);
            }
        });

        jButtonSalvarLancamento.setText("Salvar");
        jButtonSalvarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarLancamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LancamentoLayout = new javax.swing.GroupLayout(Lancamento);
        Lancamento.setLayout(LancamentoLayout);
        LancamentoLayout.setHorizontalGroup(
            LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LancamentoLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addComponent(jButtonNovoLancamento)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonSalvarLancamento))
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDebito))
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCredito))
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHistorico))
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(747, Short.MAX_VALUE))
        );
        LancamentoLayout.setVerticalGroup(
            LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LancamentoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LancamentoLayout.createSequentialGroup()
                        .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(jTextFieldCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(LancamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoLancamento)
                    .addComponent(jButtonSalvarLancamento))
                .addGap(34, 34, 34))
        );

        Principal.add(Lancamento, "Lancamento");

        jLabel3.setText("Conta Corrente:");

        jLabel2.setText("Cliente:");

        jLabel1.setText("Código:");

        jLabelCodigo.setText("0");

        jButtonUsuario.setText("Cadastrar Usuário ");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jButtonSaldo.setText("Saldo");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonExtrato.setText("Extrato");
        jButtonExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtratoActionPerformed(evt);
            }
        });

        jButtonLancamento.setText("Lançamento");
        jButtonLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancamentoActionPerformed(evt);
            }
        });

        jButton1.setText("Sair ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonUsuario)
                .addGap(210, 210, 210)
                .addComponent(jButtonSaldo)
                .addGap(250, 250, 250)
                .addComponent(jButtonExtrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jButtonLancamento)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabelCodigo)
                                .addComponent(jLabelContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUsuario)
                    .addComponent(jButtonSaldo)
                    .addComponent(jButtonExtrato)
                    .addComponent(jButtonLancamento))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarContaActionPerformed
           // TODO add your handling code here:
        if (jTextFieldNumeroConta.getText().isEmpty()|| jPasswordFieldSenhaConta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Informe o úsuário e a senha");
            return;
        }
        usuarioQuery = entityManager.createQuery("SELECT u FROM Usuario u WHERE "
                + "u.conta = '" + jTextFieldNumeroConta.getText() + "' AND u.senha = '"
                + jPasswordFieldSenhaConta.getText() + "'");
        usuarioList = usuarioQuery.getResultList();
        if (usuarioList.isEmpty()){
            JOptionPane.showMessageDialog(null,"Úsuário ou senha incorretos");
        } else {
            
            // Conta e usuário         
         for (Usuario u: usuarioList){        
            jLabelContaCorrente.setText(" " +u.getConta());
            jLabelNomeCliente.setText(" " +u.getNome());
            jLabelCodigo.setText(String.valueOf(u.getCodigo()));
         }
         // Liberar opções
         jButtonSaldo.setEnabled(true);
         jButtonExtrato.setEnabled(true);
         jButtonLancamento.setEnabled(true);
         // Abrir painel Lancamentos, para evitar que usuario clique em acessar novamente
         CardLayout card = (CardLayout) Principal.getLayout();
         card.show(Principal,"Saldo");            
        } 
                    
    }//GEN-LAST:event_jButtonAcessarContaActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
         // TODO add your handling code here:
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal,"Login1"); 
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
         // TODO add your handling code here:
         CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal,"Saldo"); 
        
        //calcular 
        double credito, debito;
        String saldo; 
        
        //credito 
        movimentoQuery = entityManager.createQuery("SELECT sum(m.credito) FROM Movimento m WHERE m.usuario=" + jLabelCodigo.getText());
        credito = Double.parseDouble(movimentoQuery.getSingleResult(). toString());
        //debito
        movimentoQuery = entityManager.createQuery("Select sum(m.debito) FROM Movimento m WHERE m.usuario=" + jLabelCodigo.getText());
        debito  = Double.parseDouble(movimentoQuery.getSingleResult().toString());
        DecimalFormat f  = new DecimalFormat("#0.00");
        saldo = f.format(credito-debito);
        jTextFieldSaldo.setText(saldo);
        
    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtratoActionPerformed
          // TODO add your handling code here:
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal,"Extrato"); 
        movimentoQuery = entityManager.createQuery("SELECT m FROM Movimento m WHERE m.usuario="
                + jLabelCodigo.getText());
        movimentoList = movimentoQuery.getResultList();
                atualizarTabela();
    }//GEN-LAST:event_jButtonExtratoActionPerformed

    private void jButtonLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancamentoActionPerformed
         // TODO add your handling code here:
        CardLayout card = (CardLayout) Principal.getLayout();
        card.show(Principal,"Lancamento"); 
    }//GEN-LAST:event_jButtonLancamentoActionPerformed

    private void jButtonSalvarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarLancamentoActionPerformed
            // TODO add your handling code here:
        Double credito, debito;
        Date data = null ;
        
        try{
            entityManager.getTransaction().begin();
            Movimento movimento = new Movimento ();
            /// Converter string para data 
            DateFormat formadata = new SimpleDateFormat("dd/MM/yyyy");
            try {
                data = formadata.parse(jFormattedTextFieldData.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Terminal.class.getName()).log(Level.SEVERE, null, ex);
            }
            movimento.setData(data);
            movimento.setHistorico(jTextFieldHistorico.getText());
            //checar se o campo de credito esta preenchido 
            if (jTextFieldCredito.getText().isEmpty()){
                credito = 0.00;
            }else{
             //convertendo de Strng para double 
                credito = Double.parseDouble(jTextFieldCredito.getText());
            }
            //convertendo double para bigdecimal
            movimento.setCredito(BigDecimal.valueOf(credito));
            //Checar se o campo está preenchido 
            if (jTextFieldDebito.getText().isEmpty()){
                debito = 0.00;
            } else {
                // onverter double 
                debito = Double.parseDouble(jTextFieldDebito.getText());
            }
            //converter o double para BigDecimal 
            movimento.setDebito(BigDecimal.valueOf(debito));
            movimento.setUsuario(Integer.parseInt(jLabelCodigo.getText()));
            entityManager.persist(movimento);
            entityManager.getTransaction().commit();
            JOptionPane.showMessageDialog(null,"Registro salvo com sucesso","Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
            
        }catch (Exception e ){
            entityManager.getTransaction().rollback();
            JOptionPane.showMessageDialog(this,"Ocorreu um erro em seu registro. \n"
               + e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSalvarLancamentoActionPerformed

    private void jButtonNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoLancamentoActionPerformed
          // TODO add your handling code here:
    jFormattedTextFieldData.setText("");
    jTextFieldHistorico.setText("");
    jTextFieldCredito.setText("");
    jTextFieldDebito.setText("");
        
    }//GEN-LAST:event_jButtonNovoLancamentoActionPerformed

    private void jTextFieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           // TODO add your handling code here:
        String dataInicial, dataFinal;
        Date datai, dataf;
        String saldo;
        Double credito, debito;
        if (jTextFielddatainicial.getText().isEmpty() || jTextFielddatafinal.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Informe a data inicial e a data final", "ERRO" , JOptionPane.ERROR_MESSAGE);
                return;
        } try {
            DateFormat formadata = new SimpleDateFormat("dd/MM/yyyy");
            datai = formadata.parse(jTextFielddatainicial.getText());
            dataf = formadata.parse(jTextFielddatafinal.getText());
            
        //Trasformando para String
            DateFormat formastring = new SimpleDateFormat("yyyy-MM-dd");
            dataInicial = formastring.format(datai);
             dataFinal = formastring.format(dataf);
             //calculando o credito
             movimentoQuery = entityManager.createQuery("SELECT sum(m.credito) FROM Movimento m WHERE m.usuario = "
                     +jLabelCodigo.getText()+ "and m.data >= ' " +dataInicial+
                     "'and m.data <= '" +dataFinal+"'" );
         credito = Double.parseDouble(movimentoQuery.getSingleResult().toString());
         //calculando debito
         movimentoQuery = entityManager.createQuery("SELECT sum(m.debito) FROM Movimento m WHERE m.usuario = "
                +jLabelCodigo.getText()+ "and m.data >= ' " +dataInicial+
                     "'and m.data <= '" +dataFinal+"'" ); 
         debito = Double.parseDouble(movimentoQuery.getSingleResult().toString());
         //Informando saldo 
         DecimalFormat f = new DecimalFormat ("#.00");
         saldo = f.format(credito-debito);
         jTextFieldsaldoextrato.setText(saldo);
         //extrato por data
         movimentoQuery = entityManager.createQuery("SELECT m FROM Movimento m WHERE m.usuario = "
                +jLabelCodigo.getText()+ "and m.data >= ' " +dataInicial+
                     "'and m.data <= '" +dataFinal+"'" ); 
                 movimentoList = movimentoQuery.getResultList();
                 atualizarTabela();
        }  catch (ParseException ex) {          
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir este registro?","Exclusão", JOptionPane.YES_NO_OPTION);
        if (resposta == 1){
            return;
        }
        try {
            //pegar valor da linha selecionada 
            int linha=jTable1.getSelectedRow();
            //pegar codigo do cliente registrado 
            Object  codigo = jTable1.getValueAt(linha ,0);
            entityManager.getTransaction().begin();
            movimentoQuery = entityManager.createQuery("delete from Movimento m where m.lanc = " + codigo);
            movimentoQuery.executeUpdate();
            entityManager.getTransaction().commit();
            movimentoQuery= entityManager.createQuery("select m from Movimento m where m.usuario= " + jLabelCodigo.getText());
            movimentoList=movimentoQuery.getResultList();
            atualizarTabela();
            JOptionPane.showMessageDialog(null, "Registro excluido com sucesso ");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu um erro ao excluir o lançamento.\n" + e.getMessage()+ "Erro.\n" + JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }
    
    public void atualizarTabela(){
        

jTable1 = new javax.swing.JTable();


org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, movimentoList, jTable1);
org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lanc}"));
columnBinding.setColumnName("Lanc");
columnBinding.setColumnClass(Integer.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${credito}"));
columnBinding.setColumnName("Credito");
columnBinding.setColumnClass(java.math.BigDecimal.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data}"));
columnBinding.setColumnName("Data");
columnBinding.setColumnClass(java.util.Date.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${debito}"));
columnBinding.setColumnName("Debito");
columnBinding.setColumnClass(java.math.BigDecimal.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${historico}"));
columnBinding.setColumnName("Historico");
columnBinding.setColumnClass(String.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
columnBinding.setColumnName("Saldo");
columnBinding.setColumnClass(java.math.BigDecimal.class);
columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${usuario}"));
columnBinding.setColumnName("Usuario");
columnBinding.setColumnClass(Integer.class);
bindingGroup.addBinding(jTableBinding);
jTableBinding.bind();

jScrollPane1.setViewportView(jTable1);
    
        
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Extrato;
    private javax.swing.JPanel Lancamento;
    private javax.swing.JPanel Login1;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Saldo;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAcessarConta;
    private javax.swing.JButton jButtonCancelarConta;
    private javax.swing.JButton jButtonExtrato;
    private javax.swing.JButton jButtonLancamento;
    private javax.swing.JButton jButtonNovoLancamento;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSalvarLancamento;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelContaCorrente;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JPasswordField jPasswordFieldSenhaConta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCredito;
    private javax.swing.JTextField jTextFieldDebito;
    private javax.swing.JTextField jTextFieldHistorico;
    private javax.swing.JTextField jTextFieldNumeroConta;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFielddatafinal;
    private javax.swing.JTextField jTextFielddatainicial;
    private javax.swing.JTextField jTextFieldsaldoextrato;
    private java.util.List<revisaocaixa.Movimento> movimentoList;
    private javax.persistence.Query movimentoQuery;
    private java.util.List<revisaocaixa.Usuario> usuarioList;
    private javax.persistence.Query usuarioQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
