
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author INFO01
 */
public class PaginaIniciar extends javax.swing.JFrame {

    double profundidade,comprimento,largura,areaTotal=0,valorTotal,areaLateral,arealateral2,
            areafundo,acabamento=0;
    String totalPagarFormatado;
    /**
     * Creates new form PaginaIniciar
     */
    public PaginaIniciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acabamentoButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LarguaraTExto = new javax.swing.JLabel();
        ComprimentoTexto = new javax.swing.JLabel();
        ProfundidadeTexto = new javax.swing.JLabel();
        LarguraTextField = new javax.swing.JTextField();
        ComprimentoTextField = new javax.swing.JTextField();
        ProfundidadeTextField = new javax.swing.JTextField();
        AzulejosimplesRadioButton = new javax.swing.JRadioButton();
        AcabamentoTexto = new javax.swing.JLabel();
        PorcelanaChinesaRadioButton = new javax.swing.JRadioButton();
        TitanioRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        CalcularButton = new javax.swing.JButton();
        LimparButton = new javax.swing.JButton();
        TotalPagarTexto = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();
        PiscinasOrg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivoMenu = new javax.swing.JMenu();
        SairMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piscinas Org");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "", 0, 0, null, java.awt.Color.white));

        LarguaraTExto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        LarguaraTExto.setText("Largura (m):");

        ComprimentoTexto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        ComprimentoTexto.setText("Comprimento (m):");

        ProfundidadeTexto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        ProfundidadeTexto.setText("Profundidade (m):");

        LarguraTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LarguraTextField.setText("0");
        LarguraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LarguraTextFieldActionPerformed(evt);
            }
        });

        ComprimentoTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ComprimentoTextField.setText("0");

        ProfundidadeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ProfundidadeTextField.setText("0");

        AzulejosimplesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        acabamentoButtonGroup.add(AzulejosimplesRadioButton);
        AzulejosimplesRadioButton.setSelected(true);
        AzulejosimplesRadioButton.setText("Azulejo Simples(R$ 2,00/m²)");

        AcabamentoTexto.setBackground(new java.awt.Color(204, 204, 204));
        AcabamentoTexto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        AcabamentoTexto.setText("     Acabamento");
        AcabamentoTexto.setOpaque(true);

        PorcelanaChinesaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        acabamentoButtonGroup.add(PorcelanaChinesaRadioButton);
        PorcelanaChinesaRadioButton.setText("Porcelana Chinesa(R$ 4,00/m²)");

        TitanioRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        acabamentoButtonGroup.add(TitanioRadioButton);
        TitanioRadioButton.setText("Titánio(R$ 10,00/m²)");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CalcularButton.setText("Calcular");
        CalcularButton.setToolTipText("Calcula o Valor Da piscina");
        CalcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularButtonActionPerformed(evt);
            }
        });

        LimparButton.setText("Limpar");
        LimparButton.setToolTipText("Limpa Todos Os Dados ");
        LimparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparButtonActionPerformed(evt);
            }
        });

        TotalPagarTexto.setBackground(new java.awt.Color(255, 255, 255));
        TotalPagarTexto.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        TotalPagarTexto.setText("Total a Pagar:");

        ValorTotalLabel.setBackground(new java.awt.Color(255, 255, 255));
        ValorTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ValorTotalLabel.setForeground(new java.awt.Color(0, 0, 255));
        ValorTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValorTotalLabel.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TitanioRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PorcelanaChinesaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AzulejosimplesRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addComponent(AcabamentoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProfundidadeTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addComponent(ComprimentoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LarguaraTExto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LarguraTextField)
                                    .addComponent(ComprimentoTextField)
                                    .addComponent(ProfundidadeTextField))
                                .addGap(10, 10, 10)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(CalcularButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LimparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(75, 75, 75)
                .addComponent(jSeparator1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TotalPagarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LarguaraTExto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LarguraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ComprimentoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ComprimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ProfundidadeTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ProfundidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(AcabamentoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AzulejosimplesRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PorcelanaChinesaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitanioRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcularButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LimparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TotalPagarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170))
        );

        PiscinasOrg.setBackground(new java.awt.Color(255, 0, 0));
        PiscinasOrg.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 24)); // NOI18N
        PiscinasOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PiscinasOrg.setText("Piscinas LFC");
        PiscinasOrg.setOpaque(true);

        ArquivoMenu.setText("Arquivo");
        ArquivoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArquivoMenuActionPerformed(evt);
            }
        });

        SairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        SairMenuItem.setText("Sair");
        SairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairMenuItemActionPerformed(evt);
            }
        });
        ArquivoMenu.add(SairMenuItem);

        jMenuBar1.add(ArquivoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PiscinasOrg, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PiscinasOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LarguraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LarguraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LarguraTextFieldActionPerformed

    private void CalcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularButtonActionPerformed
      
        DecimalFormat formato =new DecimalFormat("R$#,##0.00");
          if (LarguraTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verifica si digitos o campo de largura Correto",
                    "Atençao",JOptionPane.ERROR_MESSAGE);
            LarguraTextField.requestFocus();
            return;
        }
           if (ProfundidadeTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verifica si digitos o campo de Profundidade Correto",
                    "Atençao",JOptionPane.ERROR_MESSAGE);
            ProfundidadeTextField.requestFocus();
            return;
        }
            if (ComprimentoTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verifica si digitos o campo de Comprimento Correto",
                    "Atençao",JOptionPane.ERROR_MESSAGE);
            ComprimentoTextField.requestFocus();
            return;
        }
      try{
        profundidade=Double.parseDouble(ProfundidadeTextField.getText());
        comprimento=Double.parseDouble(ComprimentoTextField.getText());
        largura=Double.parseDouble(LarguraTextField.getText());
        
        areafundo=comprimento*largura;
        areaLateral=largura*profundidade;
        arealateral2=comprimento*profundidade;
        areaTotal=areafundo+areaLateral+arealateral2;
      
        if (AzulejosimplesRadioButton.isSelected()) {
        acabamento=2;  
        }
        if (PorcelanaChinesaRadioButton.isSelected()) {
            acabamento=4;
        }
        if (TitanioRadioButton.isSelected()) {
            acabamento=10;
        }
        
        valorTotal=areaTotal*acabamento;
        
       totalPagarFormatado=formato.format(valorTotal);
       ValorTotalLabel.setText(totalPagarFormatado);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro "+e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
 
    }//GEN-LAST:event_CalcularButtonActionPerformed

    private void LimparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparButtonActionPerformed
        ComprimentoTextField.setText("0");
        LarguraTextField.setText("0");
        ProfundidadeTextField.setText("0");
       AzulejosimplesRadioButton.setSelected(true);
        ValorTotalLabel.setText("R$0,00");
    }//GEN-LAST:event_LimparButtonActionPerformed

    private void ArquivoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArquivoMenuActionPerformed
        
    }//GEN-LAST:event_ArquivoMenuActionPerformed

    private void SairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairMenuItemActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Confirmar", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE)==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SairMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaIniciar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcabamentoTexto;
    private javax.swing.JMenu ArquivoMenu;
    private javax.swing.JRadioButton AzulejosimplesRadioButton;
    private javax.swing.JButton CalcularButton;
    private javax.swing.JTextField ComprimentoTextField;
    private javax.swing.JLabel ComprimentoTexto;
    private javax.swing.JLabel LarguaraTExto;
    private javax.swing.JTextField LarguraTextField;
    private javax.swing.JButton LimparButton;
    private javax.swing.JLabel PiscinasOrg;
    private javax.swing.JRadioButton PorcelanaChinesaRadioButton;
    private javax.swing.JTextField ProfundidadeTextField;
    private javax.swing.JLabel ProfundidadeTexto;
    private javax.swing.JMenuItem SairMenuItem;
    private javax.swing.JRadioButton TitanioRadioButton;
    private javax.swing.JLabel TotalPagarTexto;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.ButtonGroup acabamentoButtonGroup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
