
import java.awt.Color;
import javax.swing.text.StyledEditorKit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author INFO01
 */
public class TelaGelageira extends javax.swing.JFrame {

    int ligarDesligar = 0;
    double temperaturaGeladeira = 0;
    double temperaturaFreezer = 0;
    //pegar dados da classe geladeira
    geladeira Geladeira = new geladeira();

    /**
     * Creates new form TelaGelageira
     */
    public TelaGelageira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telaTemperaturaFreezerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telaTemperaturaGeladeiraLabel = new javax.swing.JLabel();
        diminuirTemperaturaGeladeiraButton = new javax.swing.JButton();
        aumentarTemperaturaGeladeiraButton = new javax.swing.JButton();
        diminuirTemperaturaGeladeira30Button = new javax.swing.JButton();
        aumentarTemperaturaGeladeira15Button = new javax.swing.JButton();
        diminuirTemperaturaFreezer50Button = new javax.swing.JButton();
        diminuirTemperaturaFreezerButton = new javax.swing.JButton();
        aumentarTemperaturaFreezerButton = new javax.swing.JButton();
        aumentarTemperaturaFreezer10Button = new javax.swing.JButton();
        ligarDesligarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), "Geladeira LFC"));

        jLabel1.setText("Temperatura Atua da geladeiral:");

        telaTemperaturaFreezerLabel.setBackground(new java.awt.Color(0, 0, 0));
        telaTemperaturaFreezerLabel.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 18)); // NOI18N
        telaTemperaturaFreezerLabel.setOpaque(true);

        jLabel2.setText("Temperatura Atua da Freezer:");

        telaTemperaturaGeladeiraLabel.setBackground(new java.awt.Color(0, 0, 0));
        telaTemperaturaGeladeiraLabel.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 18)); // NOI18N
        telaTemperaturaGeladeiraLabel.setOpaque(true);

        diminuirTemperaturaGeladeiraButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        diminuirTemperaturaGeladeiraButton.setText("<");
        diminuirTemperaturaGeladeiraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diminuirTemperaturaGeladeiraButtonActionPerformed(evt);
            }
        });

        aumentarTemperaturaGeladeiraButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aumentarTemperaturaGeladeiraButton.setText(">");
        aumentarTemperaturaGeladeiraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarTemperaturaGeladeiraButtonActionPerformed(evt);
            }
        });

        diminuirTemperaturaGeladeira30Button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        diminuirTemperaturaGeladeira30Button.setText("- 30");
        diminuirTemperaturaGeladeira30Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diminuirTemperaturaGeladeira30ButtonActionPerformed(evt);
            }
        });

        aumentarTemperaturaGeladeira15Button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aumentarTemperaturaGeladeira15Button.setText("15");
        aumentarTemperaturaGeladeira15Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarTemperaturaGeladeira15ButtonActionPerformed(evt);
            }
        });

        diminuirTemperaturaFreezer50Button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        diminuirTemperaturaFreezer50Button.setText("-50");
        diminuirTemperaturaFreezer50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diminuirTemperaturaFreezer50ButtonActionPerformed(evt);
            }
        });

        diminuirTemperaturaFreezerButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        diminuirTemperaturaFreezerButton.setText("<");
        diminuirTemperaturaFreezerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diminuirTemperaturaFreezerButtonActionPerformed(evt);
            }
        });

        aumentarTemperaturaFreezerButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aumentarTemperaturaFreezerButton.setText(">");
        aumentarTemperaturaFreezerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarTemperaturaFreezerButtonActionPerformed(evt);
            }
        });

        aumentarTemperaturaFreezer10Button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aumentarTemperaturaFreezer10Button.setText("10");
        aumentarTemperaturaFreezer10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarTemperaturaFreezer10ButtonActionPerformed(evt);
            }
        });

        ligarDesligarButton.setText("Ligar / Desligar");
        ligarDesligarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarDesligarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(diminuirTemperaturaGeladeira30Button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(diminuirTemperaturaGeladeiraButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(aumentarTemperaturaGeladeiraButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(aumentarTemperaturaGeladeira15Button))
                        .addComponent(telaTemperaturaGeladeiraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(diminuirTemperaturaFreezer50Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diminuirTemperaturaFreezerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aumentarTemperaturaFreezerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aumentarTemperaturaFreezer10Button))
                    .addComponent(telaTemperaturaFreezerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ligarDesligarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaTemperaturaGeladeiraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diminuirTemperaturaGeladeiraButton)
                    .addComponent(aumentarTemperaturaGeladeiraButton)
                    .addComponent(diminuirTemperaturaGeladeira30Button)
                    .addComponent(aumentarTemperaturaGeladeira15Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaTemperaturaFreezerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diminuirTemperaturaFreezerButton)
                    .addComponent(aumentarTemperaturaFreezerButton)
                    .addComponent(diminuirTemperaturaFreezer50Button)
                    .addComponent(aumentarTemperaturaFreezer10Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(ligarDesligarButton)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ligarDesligarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarDesligarButtonActionPerformed

        ligarDesligar++;
        if (ligarDesligar % 2 == 1) {
            Geladeira.ligar();
            telaTemperaturaFreezerLabel.setForeground(new Color(255, 255, 255));
            telaTemperaturaGeladeiraLabel.setForeground(new Color(255, 255, 255));
            temperaturaGeladeira();
            temperaturaFrezer();
        } else {
            Geladeira.desligar();
            telaTemperaturaFreezerLabel.setForeground(new Color(0, 0, 0));
            telaTemperaturaGeladeiraLabel.setForeground(new Color(0, 0, 0));
            temperaturaGeladeira();
            temperaturaFrezer();
        }
    }//GEN-LAST:event_ligarDesligarButtonActionPerformed

    //Geladeira
    private void diminuirTemperaturaGeladeira30ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diminuirTemperaturaGeladeira30ButtonActionPerformed
        Geladeira.diminuirTemperaturaGeladeira();
        temperaturaGeladeira();
    }//GEN-LAST:event_diminuirTemperaturaGeladeira30ButtonActionPerformed

    private void aumentarTemperaturaGeladeira15ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarTemperaturaGeladeira15ButtonActionPerformed
        Geladeira.aumentarTemperaturaGeladeira();
        temperaturaGeladeira();
    }//GEN-LAST:event_aumentarTemperaturaGeladeira15ButtonActionPerformed

    private void diminuirTemperaturaGeladeiraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diminuirTemperaturaGeladeiraButtonActionPerformed
        temperaturaGeladeira--;
        Geladeira.setTemperaturaGeladeira(temperaturaGeladeira);
        temperaturaGeladeira();
    }//GEN-LAST:event_diminuirTemperaturaGeladeiraButtonActionPerformed

    private void aumentarTemperaturaGeladeiraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarTemperaturaGeladeiraButtonActionPerformed
        temperaturaGeladeira++;
        Geladeira.setTemperaturaGeladeira(temperaturaGeladeira);
        temperaturaGeladeira();
    }//GEN-LAST:event_aumentarTemperaturaGeladeiraButtonActionPerformed

    //Freezer
    private void diminuirTemperaturaFreezer50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diminuirTemperaturaFreezer50ButtonActionPerformed
        Geladeira.diminuirTemperaturaFreezer();
        temperaturaFrezer();
    }//GEN-LAST:event_diminuirTemperaturaFreezer50ButtonActionPerformed

    private void diminuirTemperaturaFreezerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diminuirTemperaturaFreezerButtonActionPerformed
        temperaturaFreezer--;
        Geladeira.setTemperaturaFreezer(temperaturaFreezer);
        temperaturaFrezer();
    }//GEN-LAST:event_diminuirTemperaturaFreezerButtonActionPerformed

    private void aumentarTemperaturaFreezerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarTemperaturaFreezerButtonActionPerformed
        temperaturaFreezer++;
        Geladeira.setTemperaturaFreezer(temperaturaFreezer);
        temperaturaFrezer();
    }//GEN-LAST:event_aumentarTemperaturaFreezerButtonActionPerformed

    private void aumentarTemperaturaFreezer10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarTemperaturaFreezer10ButtonActionPerformed
        Geladeira.aumentarTemperaturaFreezer();
        temperaturaFrezer();
    }//GEN-LAST:event_aumentarTemperaturaFreezer10ButtonActionPerformed

    public void temperaturaGeladeira() {
        temperaturaGeladeira = Geladeira.getTemperaturaGeladeira();
        telaTemperaturaGeladeiraLabel.setText(String.valueOf(temperaturaGeladeira));

    }

    public void temperaturaFrezer() {
        temperaturaFreezer = Geladeira.getTemperaturaFreezer();
        telaTemperaturaFreezerLabel.setText(String.valueOf(temperaturaFreezer));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGelageira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGelageira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGelageira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGelageira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGelageira().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarTemperaturaFreezer10Button;
    private javax.swing.JButton aumentarTemperaturaFreezerButton;
    private javax.swing.JButton aumentarTemperaturaGeladeira15Button;
    private javax.swing.JButton aumentarTemperaturaGeladeiraButton;
    private javax.swing.JButton diminuirTemperaturaFreezer50Button;
    private javax.swing.JButton diminuirTemperaturaFreezerButton;
    private javax.swing.JButton diminuirTemperaturaGeladeira30Button;
    private javax.swing.JButton diminuirTemperaturaGeladeiraButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ligarDesligarButton;
    private javax.swing.JLabel telaTemperaturaFreezerLabel;
    private javax.swing.JLabel telaTemperaturaGeladeiraLabel;
    // End of variables declaration//GEN-END:variables
}
