
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Felipe & Rayssan
 */
public class TelaTV extends javax.swing.JFrame {

    int volumeTV, canal;
    Televisor tv1 = new Televisor();
    Televisor tv2 = new Televisor();
    Televisor tv3 = new Televisor();
    Televisor tv4 = new Televisor();
    Televisor tv5 = new Televisor();

    /**
     * Creates new form TelaTV
     */
    public TelaTV() {
        initComponents();
        ligarDesligarButton.setBackground(new Color(0, 0, 0, 0));
        setIconImage(getToolkit().createImage(getClass().getResource("television-18-xl.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tvbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tv1RadioButton = new javax.swing.JRadioButton();
        tv2RadioButton = new javax.swing.JRadioButton();
        tv3RadioButton = new javax.swing.JRadioButton();
        tv4RadioButton = new javax.swing.JRadioButton();
        tv5RadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marcaTextField = new javax.swing.JTextField();
        polegadasTextField = new javax.swing.JTextField();
        telaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        canalLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        mudarCanalButton = new javax.swing.JButton();
        aumentarVolumeButton = new javax.swing.JButton();
        diminuirVolumeButton = new javax.swing.JButton();
        ligarDesligarButton = new javax.swing.JButton();
        ligarDesligarLabel = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sairMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Onofre's TV's");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "TV's", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(255, 51, 0))); // NOI18N

        tv1RadioButton.setBackground(new java.awt.Color(0, 0, 0));
        tvbuttonGroup.add(tv1RadioButton);
        tv1RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tv1RadioButton.setText("1");
        tv1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv1RadioButtonActionPerformed(evt);
            }
        });

        tv2RadioButton.setBackground(new java.awt.Color(0, 0, 0));
        tvbuttonGroup.add(tv2RadioButton);
        tv2RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tv2RadioButton.setText("2");
        tv2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv2RadioButtonActionPerformed(evt);
            }
        });

        tv3RadioButton.setBackground(new java.awt.Color(0, 0, 0));
        tvbuttonGroup.add(tv3RadioButton);
        tv3RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tv3RadioButton.setText("3");
        tv3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv3RadioButtonActionPerformed(evt);
            }
        });

        tv4RadioButton.setBackground(new java.awt.Color(0, 0, 0));
        tvbuttonGroup.add(tv4RadioButton);
        tv4RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tv4RadioButton.setText("4");
        tv4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv4RadioButtonActionPerformed(evt);
            }
        });

        tv5RadioButton.setBackground(new java.awt.Color(0, 0, 0));
        tvbuttonGroup.add(tv5RadioButton);
        tv5RadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tv5RadioButton.setText("5");
        tv5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tv5RadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tv1RadioButton)
                .addGap(60, 60, 60)
                .addComponent(tv2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tv3RadioButton)
                .addGap(54, 54, 54)
                .addComponent(tv4RadioButton)
                .addGap(54, 54, 54)
                .addComponent(tv5RadioButton)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv1RadioButton)
                    .addComponent(tv2RadioButton)
                    .addComponent(tv3RadioButton)
                    .addComponent(tv4RadioButton)
                    .addComponent(tv5RadioButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/television-18-xl.png"))); // NOI18N
        jLabel1.setText("ONOFRE'S TV's");
        jLabel1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Polegadas:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tela:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(polegadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(polegadasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(telaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Canal");

        canalLabel.setBackground(new java.awt.Color(0, 0, 0));
        canalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        canalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canalLabel.setText("1");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Volume");

        volumeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setText("2");

        mudarCanalButton.setText("Mudar Canal");
        mudarCanalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarCanalButtonActionPerformed(evt);
            }
        });

        aumentarVolumeButton.setText("+");
        aumentarVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarVolumeButtonActionPerformed(evt);
            }
        });

        diminuirVolumeButton.setText("-");
        diminuirVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diminuirVolumeButtonActionPerformed(evt);
            }
        });

        ligarDesligarButton.setBackground(new java.awt.Color(0, 0, 0));
        ligarDesligarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power-off-64x64.png"))); // NOI18N
        ligarDesligarButton.setOpaque(false);
        ligarDesligarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarDesligarButtonActionPerformed(evt);
            }
        });

        ligarDesligarLabel.setBackground(new java.awt.Color(0, 0, 0));
        ligarDesligarLabel.setFont(new java.awt.Font("Bell Gothic Std Black", 1, 70)); // NOI18N
        ligarDesligarLabel.setForeground(new java.awt.Color(255, 0, 0));
        ligarDesligarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligarDesligarLabel.setText("•");
        ligarDesligarLabel.setOpaque(true);

        salvarButton.setBackground(new java.awt.Color(255, 255, 255));
        salvarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo.gif"))); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mudarCanalButton)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(diminuirVolumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aumentarVolumeButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ligarDesligarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salvarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ligarDesligarLabel)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(canalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mudarCanalButton))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aumentarVolumeButton)
                            .addComponent(diminuirVolumeButton)))
                    .addComponent(ligarDesligarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligarDesligarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarButton)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Arquivo");

        sairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sairMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btSair.gif"))); // NOI18N
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tv1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv1RadioButtonActionPerformed
        LigarDesligarTela();
        marcaTextField.setText(String.valueOf(tv1.getMarca()));
        polegadasTextField.setText(String.valueOf(tv1.getPolegadas()));
        telaTextField.setText(String.valueOf(tv1.getTela()));
        canalLabel.setText(String.valueOf(tv1.getCanal()));
        volumeLabel.setText(String.valueOf(tv1.getVolume()));
    }//GEN-LAST:event_tv1RadioButtonActionPerformed

    private void tv2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv2RadioButtonActionPerformed
        LigarDesligarTela();
        marcaTextField.setText(String.valueOf(tv2.getMarca()));
        polegadasTextField.setText(String.valueOf(tv2.getPolegadas()));
        telaTextField.setText(String.valueOf(tv2.getTela()));
        canalLabel.setText(String.valueOf(tv2.getCanal()));
        volumeLabel.setText(String.valueOf(tv2.getVolume()));
    }//GEN-LAST:event_tv2RadioButtonActionPerformed

    private void tv3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv3RadioButtonActionPerformed
        LigarDesligarTela();
        marcaTextField.setText(String.valueOf(tv3.getMarca()));
        polegadasTextField.setText(String.valueOf(tv3.getPolegadas()));
        telaTextField.setText(String.valueOf(tv3.getTela()));
        canalLabel.setText(String.valueOf(tv3.getCanal()));
        volumeLabel.setText(String.valueOf(tv3.getVolume()));
    }//GEN-LAST:event_tv3RadioButtonActionPerformed

    private void tv4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv4RadioButtonActionPerformed
        LigarDesligarTela();
        marcaTextField.setText(String.valueOf(tv4.getMarca()));
        polegadasTextField.setText(String.valueOf(tv4.getPolegadas()));
        telaTextField.setText(String.valueOf(tv4.getTela()));
        canalLabel.setText(String.valueOf(tv4.getCanal()));
        volumeLabel.setText(String.valueOf(tv4.getVolume()));
    }//GEN-LAST:event_tv4RadioButtonActionPerformed

    private void tv5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tv5RadioButtonActionPerformed
        LigarDesligarTela();
        marcaTextField.setText(String.valueOf(tv5.getMarca()));
        polegadasTextField.setText(String.valueOf(tv5.getPolegadas()));
        telaTextField.setText(String.valueOf(tv5.getTela()));
        canalLabel.setText(String.valueOf(tv5.getCanal()));
        volumeLabel.setText(String.valueOf(tv5.getVolume()));
    }//GEN-LAST:event_tv5RadioButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed

        if (tv1RadioButton.isSelected()) {
            tv1.setMarca(marcaTextField.getText());
            tv1.setTela(telaTextField.getText());
            tv1.setPolegadas(Double.parseDouble(polegadasTextField.getText()));
        } else {
            if (tv2RadioButton.isSelected()) {
                tv2.setMarca(marcaTextField.getText());
                tv2.setTela(telaTextField.getText());
                tv2.setPolegadas(Double.parseDouble(polegadasTextField.getText()));
            } else {
                if (tv3RadioButton.isSelected()) {
                    tv3.setMarca(marcaTextField.getText());
                    tv3.setTela(telaTextField.getText());
                    tv3.setPolegadas(Double.parseDouble(polegadasTextField.getText()));
                } else {
                    if (tv4RadioButton.isSelected()) {
                        tv4.setMarca(marcaTextField.getText());
                        tv4.setTela(telaTextField.getText());
                        tv4.setPolegadas(Double.parseDouble(polegadasTextField.getText()));
                    } else {
                        if (tv5RadioButton.isSelected()) {
                            tv5.setMarca(marcaTextField.getText());
                            tv5.setTela(telaTextField.getText());
                            tv5.setPolegadas(Double.parseDouble(polegadasTextField.getText()));
                        } else {
                            Mensagem("Verifica se selecional a tv");
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_salvarButtonActionPerformed

    private void ligarDesligarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarDesligarButtonActionPerformed
        if (tv1RadioButton.isSelected()) {
            tv1.setLigarDesligar();
            LigarDesligarTela();
        } else {
            if (tv2RadioButton.isSelected()) {
                tv2.setLigarDesligar();
                LigarDesligarTela();
            } else {
                if (tv3RadioButton.isSelected()) {
                    tv3.setLigarDesligar();
                    LigarDesligarTela();
                } else {
                    if (tv4RadioButton.isSelected()) {
                        tv4.setLigarDesligar();
                        LigarDesligarTela();
                    } else {
                        if (tv5RadioButton.isSelected()) {
                            tv5.setLigarDesligar();
                            LigarDesligarTela();
                        } else {
                            Mensagem("Verifica se selecional a tv");
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_ligarDesligarButtonActionPerformed

    private void diminuirVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diminuirVolumeButtonActionPerformed
        // tv1
        if (tv1RadioButton.isSelected()) {
            if (tv1.isLigarDesligar() == true) {
                volumeTV = tv1.getVolume();
                volumeTV--;
                tv1.setVolume(volumeTV);
                volumeLabel.setText(String.valueOf(tv1.getVolume()));
            } else {
                Mensagem("Ligue a tv antes");

            }
        } else {
            //tv2
            if (tv2RadioButton.isSelected()) {
                if (tv2.isLigarDesligar() == true) {
                    volumeTV = tv2.getVolume();
                    volumeTV--;
                    tv2.setVolume(volumeTV);
                    volumeLabel.setText(String.valueOf(tv2.getVolume()));
                } else {
                    Mensagem("Ligue a tv antes");

                }
            } else {
                //tv3
                if (tv3RadioButton.isSelected()) {
                    if (tv3.isLigarDesligar() == true) {
                        volumeTV = tv3.getVolume();
                        volumeTV--;
                        tv3.setVolume(volumeTV);
                        volumeLabel.setText(String.valueOf(tv3.getVolume()));
                    } else {
                        Mensagem("Ligue a tv antes");

                    }
                } else {
                    //tv4
                    if (tv4RadioButton.isSelected()) {
                        if (tv4.isLigarDesligar() == true) {
                            volumeTV = tv4.getVolume();
                            volumeTV--;
                            tv4.setVolume(volumeTV);
                            volumeLabel.setText(String.valueOf(tv4.getVolume()));
                        } else {
                            Mensagem("Ligue a tv antes");

                        }
                    } else {
                        //tv5
                        if (tv5RadioButton.isSelected()) {
                            if (tv5.isLigarDesligar() == true) {
                                volumeTV = tv5.getVolume();
                                volumeTV--;
                                tv5.setVolume(volumeTV);
                                volumeLabel.setText(String.valueOf(tv5.getVolume()));
                            } else {
                                Mensagem("Ligue a tv antes");

                            }
                        } else {
                            Mensagem("Seleciona a tv antes");
                        }//fim tv5
                    }//fim tv4
                }//fim tv3
            }//fim tv2
        }//fim tv1  diminutir volume
    }//GEN-LAST:event_diminuirVolumeButtonActionPerformed

    private void mudarCanalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarCanalButtonActionPerformed
        // tv1
        if (tv1RadioButton.isSelected()) {
            if (tv1.isLigarDesligar() == true) {
                canal = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o canal"));
                tv1.setCanal(canal);
                canalLabel.setText(String.valueOf(tv1.getCanal()));
            } else {
                Mensagem("Ligue a tv antes");

            }
        } else {
            //tv2
            if (tv2RadioButton.isSelected()) {
                if (tv2.isLigarDesligar() == true) {
                    canal = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o canal"));
                    tv2.setCanal(canal);
                    canalLabel.setText(String.valueOf(tv2.getCanal()));
                } else {
                    Mensagem("Ligue a tv antes");

                }
            } else {
                //tv3
                if (tv3RadioButton.isSelected()) {
                    if (tv3.isLigarDesligar() == true) {
                        canal = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o canal"));
                        tv3.setCanal(canal);
                        canalLabel.setText(String.valueOf(tv3.getCanal()));
                    } else {
                        Mensagem("Ligue a tv antes");

                    }
                } else {
                    //tv4
                    if (tv4RadioButton.isSelected()) {
                        if (tv4.isLigarDesligar() == true) {
                            canal = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o canal"));
                            tv4.setCanal(canal);
                            canalLabel.setText(String.valueOf(tv4.getCanal()));
                        } else {
                            Mensagem("Ligue a tv antes");

                        }
                    } else {
                        //tv5
                        if (tv5RadioButton.isSelected()) {
                            if (tv5.isLigarDesligar() == true) {
                                canal = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o canal"));
                                tv5.setCanal(canal);
                                canalLabel.setText(String.valueOf(tv5.getCanal()));
                            } else {
                                Mensagem("Ligue a tv antes");

                            }
                        } else {
                            Mensagem("Seleciona a tv antes");
                        }//fim tv5
                    }//fim tv4
                }//fim tv3
            }//fim tv2
        }//fim tv1  mudar canal

    }//GEN-LAST:event_mudarCanalButtonActionPerformed

    private void aumentarVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarVolumeButtonActionPerformed
        // tv1
        if (tv1RadioButton.isSelected()) {
            if (tv1.isLigarDesligar() == true) {
                volumeTV = tv1.getVolume();
                volumeTV++;
                tv1.setVolume(volumeTV);
                volumeLabel.setText(String.valueOf(tv1.getVolume()));
            } else {
                Mensagem("Ligue a tv antes");

            }
        } else {
            //tv2
            if (tv2RadioButton.isSelected()) {
                if (tv2.isLigarDesligar() == true) {
                    volumeTV = tv2.getVolume();
                    volumeTV++;
                    tv2.setVolume(volumeTV);
                    volumeLabel.setText(String.valueOf(tv2.getVolume()));
                } else {
                    Mensagem("Ligue a tv antes");

                }
            } else {
                //tv3
                if (tv3RadioButton.isSelected()) {
                    if (tv3.isLigarDesligar() == true) {
                        volumeTV = tv3.getVolume();
                        volumeTV++;
                        tv3.setVolume(volumeTV);
                        volumeLabel.setText(String.valueOf(tv3.getVolume()));
                    } else {
                        Mensagem("Ligue a tv antes");

                    }
                } else {
                    //tv4
                    if (tv4RadioButton.isSelected()) {
                        if (tv4.isLigarDesligar() == true) {
                            volumeTV = tv4.getVolume();
                            volumeTV++;
                            tv4.setVolume(volumeTV);
                            volumeLabel.setText(String.valueOf(tv4.getVolume()));
                        } else {
                            Mensagem("Ligue a tv antes");

                        }
                    } else {
                        //tv5
                        if (tv5RadioButton.isSelected()) {
                            if (tv5.isLigarDesligar() == true) {
                                volumeTV = tv5.getVolume();
                                volumeTV++;
                                tv5.setVolume(volumeTV);
                                volumeLabel.setText(String.valueOf(tv5.getVolume()));
                            } else {
                                Mensagem("Ligue a tv antes");

                            }
                        } else {
                            Mensagem("Seleciona a tv antes");
                        }//fim tv5
                    }//fim tv4
                }//fim tv3
            }//fim tv2
        }//fim tv1  aumentar volume
    }//GEN-LAST:event_aumentarVolumeButtonActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja Sair", "Sair",
                JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairMenuItemActionPerformed

    public void LigarDesligarTela() {
        if (tv1RadioButton.isSelected()) {
            if (tv1.isLigarDesligar() == true) {
                volumeLabel.setForeground(new Color(255, 255, 255));
                canalLabel.setForeground(new Color(255, 255, 255));
                ligarDesligarLabel.setForeground(new Color(0, 255, 0));
            } else {
                volumeLabel.setForeground(new Color(0, 0, 0));
                canalLabel.setForeground(new Color(0, 0, 0));
                ligarDesligarLabel.setForeground(new Color(255, 0, 0));
            }
        } else {
            if (tv2RadioButton.isSelected()) {
                if (tv2.isLigarDesligar() == true) {
                    volumeLabel.setForeground(new Color(255, 255, 255));
                    canalLabel.setForeground(new Color(255, 255, 255));
                    ligarDesligarLabel.setForeground(new Color(0, 255, 0));
                } else {
                    volumeLabel.setForeground(new Color(0, 0, 0));
                    canalLabel.setForeground(new Color(0, 0, 0));
                    ligarDesligarLabel.setForeground(new Color(255, 0, 0));
                }
            } else {
                if (tv3RadioButton.isSelected()) {
                    if (tv3.isLigarDesligar() == true) {
                        volumeLabel.setForeground(new Color(255, 255, 255));
                        canalLabel.setForeground(new Color(255, 255, 255));
                        ligarDesligarLabel.setForeground(new Color(0, 255, 0));
                    } else {
                        volumeLabel.setForeground(new Color(0, 0, 0));
                        canalLabel.setForeground(new Color(0, 0, 0));
                        ligarDesligarLabel.setForeground(new Color(255, 0, 0));
                    }
                } else {
                    if (tv4RadioButton.isSelected()) {
                        if (tv4.isLigarDesligar() == true) {
                            volumeLabel.setForeground(new Color(255, 255, 255));
                            canalLabel.setForeground(new Color(255, 255, 255));
                            ligarDesligarLabel.setForeground(new Color(0, 255, 0));
                        } else {
                            volumeLabel.setForeground(new Color(0, 0, 0));
                            canalLabel.setForeground(new Color(0, 0, 0));
                            ligarDesligarLabel.setForeground(new Color(255, 0, 0));
                        }
                    } else {
                        if (tv5RadioButton.isSelected()) {
                            if (tv5.isLigarDesligar() == true) {
                                volumeLabel.setForeground(new Color(255, 255, 255));
                                canalLabel.setForeground(new Color(255, 255, 255));
                                ligarDesligarLabel.setForeground(new Color(0, 255, 0));
                            } else {
                                volumeLabel.setForeground(new Color(0, 0, 0));
                                canalLabel.setForeground(new Color(0, 0, 0));
                                ligarDesligarLabel.setForeground(new Color(255, 0, 0));
                            }
                        } else {
                            Mensagem("Verifica se selecionol a tv");
                        }
                    }
                }
            }
        }
    }

    public void Mensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem, "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTV().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarVolumeButton;
    private javax.swing.JLabel canalLabel;
    private javax.swing.JButton diminuirVolumeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton ligarDesligarButton;
    private javax.swing.JLabel ligarDesligarLabel;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JButton mudarCanalButton;
    private javax.swing.JTextField polegadasTextField;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JButton salvarButton;
    private javax.swing.JTextField telaTextField;
    private javax.swing.JRadioButton tv1RadioButton;
    private javax.swing.JRadioButton tv2RadioButton;
    private javax.swing.JRadioButton tv3RadioButton;
    private javax.swing.JRadioButton tv4RadioButton;
    private javax.swing.JRadioButton tv5RadioButton;
    private javax.swing.ButtonGroup tvbuttonGroup;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
