package javaapplication1;

import Carro.Carro;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas & Rayssan
 */
public class TelaCarro extends javax.swing.JFrame {

    
    Carro carro1 = new Carro();
    Carro carro2 = new Carro();
    Carro carro3 = new Carro();
    /**
     * Creates new form TelaCarro
     */
    public TelaCarro() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("o.png")));
        
        marcaTextField.setText(carro1.getMarca());
        modeloTextField.setText(carro1.getModelo());
        motorTextField.setText(String.valueOf(carro1.getMotor()));
        corTextField.setText(carro1.getCor());
        placaTextField.setText(carro1.getPlaca());
        velocidadeLabel.setText(String.valueOf(carro1.getVelocidade()));
        marchaLabel.setText(String.valueOf(carro1.getMarcha()));
        if (carro1.getLigado() == true) {
            ligadoLabel.setBackground(Color.green);
            ligadoLabel.setText("Ligado");
        } else {
            ligadoLabel.setBackground(Color.red);
            ligadoLabel.setText("Desligado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tipoCarrobuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        carro1RadioButton = new javax.swing.JRadioButton();
        carro2RadioButton = new javax.swing.JRadioButton();
        carro3RadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marcaTextField = new javax.swing.JTextField();
        modeloTextField = new javax.swing.JTextField();
        motorTextField = new javax.swing.JTextField();
        corTextField = new javax.swing.JTextField();
        placaTextField = new javax.swing.JTextField();
        salvarButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        maisVButton = new javax.swing.JButton();
        menosVButton = new javax.swing.JButton();
        velocidadeLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        marchaLabel = new javax.swing.JLabel();
        mudarMarchaButton = new javax.swing.JButton();
        ligadoLabel = new javax.swing.JLabel();
        ligarDesligarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sairMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Carros", 0, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        carro1RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarrobuttonGroup.add(carro1RadioButton);
        carro1RadioButton.setText("Carro 1");
        carro1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carro1RadioButtonActionPerformed(evt);
            }
        });

        carro2RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarrobuttonGroup.add(carro2RadioButton);
        carro2RadioButton.setText("Carro 2");
        carro2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carro2RadioButtonActionPerformed(evt);
            }
        });

        carro3RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarrobuttonGroup.add(carro3RadioButton);
        carro3RadioButton.setText("Carro 3");
        carro3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carro3RadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(carro1RadioButton)
                .addGap(172, 172, 172)
                .addComponent(carro2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carro3RadioButton)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carro1RadioButton)
                    .addComponent(carro2RadioButton)
                    .addComponent(carro3RadioButton))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Marca:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Modelo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Motor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cor: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Placa:");

        marcaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marcaTextFieldKeyPressed(evt);
            }
        });

        motorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorTextFieldActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Velocidade:");

        maisVButton.setText("+");
        maisVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisVButtonActionPerformed(evt);
            }
        });

        menosVButton.setText("-");
        menosVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosVButtonActionPerformed(evt);
            }
        });

        velocidadeLabel.setBackground(new java.awt.Color(0, 0, 0));
        velocidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        velocidadeLabel.setForeground(new java.awt.Color(255, 255, 102));
        velocidadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        velocidadeLabel.setText("3");
        velocidadeLabel.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Marcha");

        marchaLabel.setBackground(new java.awt.Color(0, 0, 0));
        marchaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        marchaLabel.setForeground(new java.awt.Color(204, 0, 51));
        marchaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marchaLabel.setText("5");
        marchaLabel.setOpaque(true);

        mudarMarchaButton.setText("Mudar Marcha");
        mudarMarchaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarMarchaButtonActionPerformed(evt);
            }
        });

        ligadoLabel.setBackground(new java.awt.Color(255, 0, 51));
        ligadoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ligadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ligadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ligadoLabel.setText("Desligado");
        ligadoLabel.setOpaque(true);

        ligarDesligarButton.setText("Ligar/Desligar");
        ligarDesligarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarDesligarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(salvarButton)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(marcaTextField)
                        .addComponent(modeloTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(motorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(corTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(ligarDesligarButton)
                            .addGap(61, 61, 61)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(placaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(velocidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(marchaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(52, 52, 52))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 45, Short.MAX_VALUE)
                                .addComponent(ligadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(menosVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maisVButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mudarMarchaButton)
                                .addGap(26, 26, 26))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(marcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(motorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(corTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarButton)
                            .addComponent(ligarDesligarButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marchaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(velocidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menosVButton)
                            .addComponent(maisVButton)
                            .addComponent(mudarMarchaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ligadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Rosewood Std Regular", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ONOFRE'S CAR");
        jLabel6.setOpaque(true);

        jMenu1.setText("Arquivos");

        sairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sairMenuItem.setBackground(new java.awt.Color(255, 255, 255));
        sairMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/btSair.gif"))); // NOI18N
        sairMenuItem.setOpaque(true);
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carro1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carro1RadioButtonActionPerformed
         marcaTextField.setText(carro1.getMarca());
         modeloTextField.setText(carro1.getModelo());
         motorTextField.setText(String.valueOf(carro1.getMotor()));
         corTextField.setText(carro1.getCor());
         placaTextField.setText(carro1.getPlaca());
         velocidadeLabel.setText(String.valueOf(carro1.getVelocidade()));
         marchaLabel.setText(String.valueOf(carro1.getMarcha()));
         if (carro1.getLigado() == true) {
            ligadoLabel.setBackground(Color.green);
            ligadoLabel.setText("Ligado");
        } else {
            ligadoLabel.setBackground(Color.red);
            ligadoLabel.setText("Desligado");
        }
    }//GEN-LAST:event_carro1RadioButtonActionPerformed

    private void ligarDesligarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarDesligarButtonActionPerformed
         // TODO add your handling code here:
        if(carro1RadioButton. isSelected()){
            carro1.partida();  
            if(carro1.getLigado() == true){
                ligadoLabel.setBackground(Color.green);
                ligadoLabel.setText("Ligado");
            } else {
                ligadoLabel.setBackground(Color.red);
                ligadoLabel.setText("Desligado");
            }
        }
        
        if (carro2RadioButton.isSelected()){
            carro2.partida();
            if (carro2.getLigado() == true){
                ligadoLabel.setBackground(Color.green);
                ligadoLabel.setText("Ligado");               
            } else {
                ligadoLabel.setBackground(Color.red);
                ligadoLabel.setText("Desligado");
            }
        }
        
        
        if (carro3RadioButton.isSelected()){
            carro3.partida();
            if(carro3.getLigado() == true){
                ligadoLabel.setBackground(Color.green);
                ligadoLabel.setText("Ligado");
            } else {
            ligadoLabel.setBackground(Color.red);
            ligadoLabel.setText("Desligado");
        }
        }
    }//GEN-LAST:event_ligarDesligarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
         // TODO add your handling code here:
        if (carro1RadioButton.isSelected()){
            carro1.setMarca(marcaTextField.getText());
            carro1.setModelo(modeloTextField.getText());
            carro1.setMotor(Double.parseDouble(motorTextField.getText()));
            carro1.setCor(corTextField.getText());
            carro1.setPlaca(placaTextField.getText());
        } else if (carro2RadioButton.isSelected()) {
            carro2.setMarca(marcaTextField.getText());
            carro2.setModelo(modeloTextField.getText());
            carro2.setMotor(Double.parseDouble(motorTextField.getText()));
            carro2.setCor(corTextField.getText());
            carro2.setPlaca(placaTextField.getText());
        } else if (carro3RadioButton.isSelected()) {
            carro3.setMarca(marcaTextField.getText());
            carro3.setModelo(modeloTextField.getText());
            carro3.setMotor(Double.parseDouble(motorTextField.getText()));
            carro3.setCor(corTextField.getText());
            carro3.setPlaca(placaTextField.getText());
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void carro2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carro2RadioButtonActionPerformed
         // TODO add your handling code here:
        marcaTextField.setText(carro2.getMarca());
        modeloTextField.setText(carro2.getModelo());
        motorTextField.setText(String.valueOf(carro2.getMotor()));
        corTextField.setText(carro2.getCor());
        placaTextField.setText(carro2.getPlaca());
        velocidadeLabel.setText(String.valueOf(carro2.getVelocidade()));
        marchaLabel.setText(String.valueOf(carro2.getMarcha()));
        if (carro2.getLigado() == true) {
            ligadoLabel.setBackground(Color.green);
            ligadoLabel.setText("Ligado");
        } else {
            ligadoLabel.setBackground(Color.red);
            ligadoLabel.setText("Desligado");
        }
    }//GEN-LAST:event_carro2RadioButtonActionPerformed

    private void carro3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carro3RadioButtonActionPerformed
         // TODO add your handling code here:
        marcaTextField.setText(carro3.getMarca());
        modeloTextField.setText(carro3.getModelo());
        motorTextField.setText(String.valueOf(carro3.getMotor()));
        corTextField.setText(carro3.getCor());
        placaTextField.setText(carro3.getPlaca());
        velocidadeLabel.setText(String.valueOf(carro3.getVelocidade()));
        marchaLabel.setText(String.valueOf(carro3.getMarcha()));
        if (carro3.getLigado() == true) {
            ligadoLabel.setBackground(Color.green);
            ligadoLabel.setText("Ligado");
        } else {
            ligadoLabel.setBackground(Color.red);
            ligadoLabel.setText("Desligado");
        }
    }//GEN-LAST:event_carro3RadioButtonActionPerformed

    private void maisVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisVButtonActionPerformed
         // TODO add your handling code here:
        if (carro1RadioButton.isSelected()){
            carro1.acelerar();
            velocidadeLabel.setText(String.valueOf(carro1.getVelocidade()));
        } else if(carro2RadioButton.isSelected()){
            carro2.acelerar();
            velocidadeLabel.setText(String.valueOf(carro2.getVelocidade()));
        } else if(carro3RadioButton.isSelected()){
            carro3.acelerar();
            velocidadeLabel.setText(String.valueOf(carro3.getVelocidade()));
        }
    }//GEN-LAST:event_maisVButtonActionPerformed

    private void menosVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosVButtonActionPerformed
         // TODO add your handling code here:
        if (carro1RadioButton.isSelected()){
            carro1.frear();
            velocidadeLabel.setText(String.valueOf(carro1.getVelocidade()));
        } else if(carro2RadioButton.isSelected()){
            carro2.frear();
            velocidadeLabel.setText(String.valueOf(carro2.getVelocidade()));
        } else if(carro3RadioButton.isSelected()){
            carro3.frear();
            velocidadeLabel.setText(String.valueOf(carro3.getVelocidade()));
        }
    }//GEN-LAST:event_menosVButtonActionPerformed

    private void mudarMarchaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarMarchaButtonActionPerformed
         // TODO add your handling code here:
        int novaMarcha;
        novaMarcha = Integer.parseInt(JOptionPane.showInputDialog(null,
                "Para qual marcha deseja passar?"));
        if (carro1RadioButton.isSelected()) {
            carro1.mudarMarcha(novaMarcha);
            marchaLabel.setText(String.valueOf(carro1.getMarcha()));
        } else if (carro2RadioButton.isSelected()) {
            carro2.mudarMarcha(novaMarcha);
            marchaLabel.setText(String.valueOf(carro2.getMarcha()));
        } else if (carro3RadioButton.isSelected()) {
            carro3.mudarMarcha(novaMarcha);
            marchaLabel.setText(String.valueOf(carro3.getMarcha()));
        }
    }//GEN-LAST:event_mudarMarchaButtonActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        if (JOptionPane.showConfirmDialog(null,"Deseja sair?","Sair",JOptionPane.YES_NO_OPTION)==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void motorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motorTextFieldActionPerformed

    private void marcaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton carro1RadioButton;
    private javax.swing.JRadioButton carro2RadioButton;
    private javax.swing.JRadioButton carro3RadioButton;
    private javax.swing.JTextField corTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel ligadoLabel;
    private javax.swing.JButton ligarDesligarButton;
    private javax.swing.JButton maisVButton;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JLabel marchaLabel;
    private javax.swing.JButton menosVButton;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JTextField motorTextField;
    private javax.swing.JButton mudarMarchaButton;
    private javax.swing.JTextField placaTextField;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JButton salvarButton;
    private javax.swing.ButtonGroup tipoCarrobuttonGroup;
    private javax.swing.JLabel velocidadeLabel;
    // End of variables declaration//GEN-END:variables

}
