/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

/**
 *
 * @author INFO01
 */
public class Principal extends javax.swing.JFrame {

    CadastroAtores cadAtores = new CadastroAtores();
    CadastroSeries cadSeries = new CadastroSeries();
    RelatorioAtor relaAtoe = new RelatorioAtor();
    RelatorioSeries relaSerie = new RelatorioSeries();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conect = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("HBO?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        Qry_altore = java.beans.Beans.isDesignTime() ? null : conect.createQuery("SELECT a FROM Atrores a");
        atores = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : Qry_altore.getResultList();
        Qry_Series = java.beans.Beans.isDesignTime() ? null : conect.createQuery("SELECT s FROM Series s");
        series = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : Qry_Series.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn_Cadastro = new javax.swing.JMenu();
        MnI_CadaAtor = new javax.swing.JMenuItem();
        MnI_CadaSeries = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnI_RelatAtores = new javax.swing.JMenuItem();
        MnI_RelatSeries = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Mn_ConAtores = new javax.swing.JMenuItem();
        Mn_ConSer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/hbo-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        Mn_Cadastro.setText("Cadastro");

        MnI_CadaAtor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MnI_CadaAtor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        MnI_CadaAtor.setText("Atores");
        MnI_CadaAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_CadaAtorActionPerformed(evt);
            }
        });
        Mn_Cadastro.add(MnI_CadaAtor);

        MnI_CadaSeries.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        MnI_CadaSeries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/film.png"))); // NOI18N
        MnI_CadaSeries.setText("Series");
        MnI_CadaSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_CadaSeriesActionPerformed(evt);
            }
        });
        Mn_Cadastro.add(MnI_CadaSeries);

        jMenuBar1.add(Mn_Cadastro);

        jMenu2.setText("Relatorios");

        MnI_RelatAtores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnI_RelatAtores.setText(" Atores");
        MnI_RelatAtores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_RelatAtoresActionPerformed(evt);
            }
        });
        jMenu2.add(MnI_RelatAtores);

        MnI_RelatSeries.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnI_RelatSeries.setText("Series");
        MnI_RelatSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_RelatSeriesActionPerformed(evt);
            }
        });
        jMenu2.add(MnI_RelatSeries);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Consulta");

        Mn_ConAtores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Mn_ConAtores.setText("Atores");
        Mn_ConAtores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_ConAtoresActionPerformed(evt);
            }
        });
        jMenu1.add(Mn_ConAtores);

        Mn_ConSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Mn_ConSer.setText("Series");
        Mn_ConSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_ConSerActionPerformed(evt);
            }
        });
        jMenu1.add(Mn_ConSer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnI_CadaAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_CadaAtorActionPerformed
        int i;
        i = 1;
        while (true) {
            Qry_altore = conect.createQuery("SELECT a FROM Atrores a WHERE a.codigo=" + String.valueOf(i));
            atores = Qry_altore.getResultList();
            if (atores.isEmpty()) {
                cadAtores.codAtor = String.valueOf(i);
                break;
            }
            i++;
        }
        cadAtores.show();
    }//GEN-LAST:event_MnI_CadaAtorActionPerformed

    private void MnI_CadaSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_CadaSeriesActionPerformed
        int i;
        i = 1;
        while (true) {
            Qry_Series = conect.createQuery("SELECT s FROM Series s WHERE s.codigo=" + String.valueOf(i));
            series = Qry_Series.getResultList();
            if (series.isEmpty()) {
                cadSeries.codSer = String.valueOf(i);
                break;
            }
            i++;
        }
        cadSeries.show();
    }//GEN-LAST:event_MnI_CadaSeriesActionPerformed

    private void MnI_RelatAtoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_RelatAtoresActionPerformed
        relaAtoe.show();
    }//GEN-LAST:event_MnI_RelatAtoresActionPerformed

    private void MnI_RelatSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_RelatSeriesActionPerformed
        relaSerie.show();
    }//GEN-LAST:event_MnI_RelatSeriesActionPerformed

    private void Mn_ConSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_ConSerActionPerformed
        ConsultaSeries x = new ConsultaSeries();
        Qry_Series = conect.createQuery("SELECT s FROM Series s");
        series = Qry_Series.getResultList();
        x.atualiza();
        x.busca=false;
        x.show();
    }//GEN-LAST:event_Mn_ConSerActionPerformed

    private void Mn_ConAtoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_ConAtoresActionPerformed
        ConsutaAtores y = new ConsutaAtores();
        Qry_altore = conect.createQuery("SELECT a FROM Atrores a");
        atores = Qry_altore.getResultList();
        y.atualiza();
        y.show();

    }//GEN-LAST:event_Mn_ConAtoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnI_CadaAtor;
    private javax.swing.JMenuItem MnI_CadaSeries;
    private javax.swing.JMenuItem MnI_RelatAtores;
    private javax.swing.JMenuItem MnI_RelatSeries;
    private javax.swing.JMenu Mn_Cadastro;
    private javax.swing.JMenuItem Mn_ConAtores;
    private javax.swing.JMenuItem Mn_ConSer;
    private javax.persistence.Query Qry_Series;
    private javax.persistence.Query Qry_altore;
    private java.util.List<Codigo.Atrores> atores;
    private javax.persistence.EntityManager conect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private java.util.List<Codigo.Series> series;
    // End of variables declaration//GEN-END:variables
}
