
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author INFO01
 */
public class PacoteViagem extends javax.swing.JFrame {

    int destino;
    int pessoas;
    String valorpessoaformatado, valorTotalFormatado;

    /**
     * Creates new form PacoteViagem
     */
    public PacoteViagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HotelbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClienteTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DestinoList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pessoasSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        diasEstradaSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        hotel3RadioButton = new javax.swing.JRadioButton();
        hotel4RadioButton = new javax.swing.JRadioButton();
        hotel5RadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        AlmocoCheckBox = new javax.swing.JCheckBox();
        jantarCheckBox = new javax.swing.JCheckBox();
        CalcularButton = new javax.swing.JButton();
        NovoButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        valorPessoaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valorTotalTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LFC Linhas Aerias");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Cliente:");

        DestinoList.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DestinoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Xibrobó do Norte", "Fim do Mundo do sul", "Nova Matusalém", "Velha Matusalém" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(DestinoList);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Destino:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Numero de pessoas:");

        pessoasSpinner.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pessoasSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        pessoasSpinner.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Dias de Estadia:");

        diasEstradaSpinner.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        diasEstradaSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Hotel:");

        hotel3RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        HotelbuttonGroup.add(hotel3RadioButton);
        hotel3RadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hotel3RadioButton.setSelected(true);
        hotel3RadioButton.setText("3 estrela");

        hotel4RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        HotelbuttonGroup.add(hotel4RadioButton);
        hotel4RadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hotel4RadioButton.setText("4 estrela");

        hotel5RadioButton.setBackground(new java.awt.Color(255, 255, 255));
        HotelbuttonGroup.add(hotel5RadioButton);
        hotel5RadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hotel5RadioButton.setText("5 estrela");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Incluir:");

        AlmocoCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        AlmocoCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        AlmocoCheckBox.setText("Almoço");

        jantarCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        jantarCheckBox.setText("Jantar");

        CalcularButton.setText("Calcular");
        CalcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularButtonActionPerformed(evt);
            }
        });

        NovoButton.setText("Novo");
        NovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Valor", 0, 0, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor de Cada Pessoa");

        valorPessoaTextField.setEditable(false);
        valorPessoaTextField.setBackground(new java.awt.Color(0, 0, 0));
        valorPessoaTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valorPessoaTextField.setForeground(new java.awt.Color(255, 255, 255));
        valorPessoaTextField.setText("R$0,00");
        valorPessoaTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        valorPessoaTextField.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor Total:");

        valorTotalTextField.setEditable(false);
        valorTotalTextField.setBackground(new java.awt.Color(0, 0, 0));
        valorTotalTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        valorTotalTextField.setForeground(new java.awt.Color(255, 255, 255));
        valorTotalTextField.setText("R$0,00");
        valorTotalTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorPessoaTextField)
                    .addComponent(valorTotalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorPessoaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(pessoasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(diasEstradaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hotel3RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(hotel4RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(hotel5RadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AlmocoCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jantarCheckBox))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CalcularButton)
                        .addGap(18, 18, 18)
                        .addComponent(NovoButton)
                        .addGap(18, 18, 18)
                        .addComponent(sairButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hotel3RadioButton)
                            .addComponent(hotel4RadioButton)
                            .addComponent(hotel5RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(AlmocoCheckBox)
                            .addComponent(jantarCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalcularButton)
                            .addComponent(NovoButton)
                            .addComponent(sairButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pessoasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diasEstradaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jMenu1.setText("Arquivos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularButtonActionPerformed
        double valorPessoa = 0, valoTotal;
        if (ClienteTextField.getText().trim().toString().isEmpty()) {
            mensagem("O cliente é Obrigratorio");
            return;
        }

        destino = DestinoList.getSelectedIndex();

        if (destino == 0) {
            valorPessoa = 1000;
        } else {
            if (destino == 1) {
                valorPessoa = 1200;
            } else {
                if (destino == 2) {
                    valorPessoa = 1400;
                } else {
                    if (destino == 3) {
                        valorPessoa = 1600;
                    } else {
                        mensagem("Escolha um destino");
                        return;
                    }
                }
            }
        }

        if (hotel3RadioButton.isSelected()) {
            valorPessoa += 50;
            if (AlmocoCheckBox.isSelected()) {
                valorPessoa += 10;
            }
            if (jantarCheckBox.isSelected()) {
                valorPessoa += 20;
            }
        }
        if (hotel4RadioButton.isSelected()) {
            valorPessoa += 70;
            if (AlmocoCheckBox.isSelected()) {
                valorPessoa += 20;
            }
            if (jantarCheckBox.isSelected()) {
                valorPessoa += 40;
            }
        }
        if (hotel5RadioButton.isSelected()) {
            valorPessoa += 100;
            if (AlmocoCheckBox.isSelected()) {
                valorPessoa += 40;
            }
            if (jantarCheckBox.isSelected()) {
                valorPessoa += 80;
            }
        }
        pessoas = (int) pessoasSpinner.getValue();
        valoTotal = valorPessoa * pessoas;
        DecimalFormat formato = new DecimalFormat("R$#,##0.00");

        valorpessoaformatado = formato.format(valorPessoa);
        valorPessoaTextField.setText(valorpessoaformatado);
        valorTotalFormatado = formato.format(valoTotal);
        valorTotalTextField.setText(valorTotalFormatado);

    }//GEN-LAST:event_CalcularButtonActionPerformed

    private void NovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoButtonActionPerformed
        ClienteTextField.setText("");
        DestinoList.setSelectedIndex(0);
        pessoasSpinner.setValue(1);
        valorPessoaTextField.setText("R$0,00");
        AlmocoCheckBox.setSelected(false);
        jantarCheckBox.setSelected(false);
        valorTotalTextField.setText("R$0,00");
        diasEstradaSpinner.setValue(1);

    }//GEN-LAST:event_NovoButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        Sair();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Sair();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void mensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem, "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }

    public void Sair() {
        if (JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Sair", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacoteViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacoteViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacoteViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacoteViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacoteViagem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AlmocoCheckBox;
    private javax.swing.JButton CalcularButton;
    private javax.swing.JTextField ClienteTextField;
    private javax.swing.JList DestinoList;
    private javax.swing.ButtonGroup HotelbuttonGroup;
    private javax.swing.JButton NovoButton;
    private javax.swing.JSpinner diasEstradaSpinner;
    private javax.swing.JRadioButton hotel3RadioButton;
    private javax.swing.JRadioButton hotel4RadioButton;
    private javax.swing.JRadioButton hotel5RadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jantarCheckBox;
    private javax.swing.JSpinner pessoasSpinner;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextField valorPessoaTextField;
    private javax.swing.JTextField valorTotalTextField;
    // End of variables declaration//GEN-END:variables
}
