
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author INFO01
 */
public class paginaIniciar extends javax.swing.JFrame {

    /**
     * Creates new form paginaIniciar
     */
    public paginaIniciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoPaobuttonGroup = new javax.swing.ButtonGroup();
        tipoCarnebuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PaoIntegralRadioButton = new javax.swing.JRadioButton();
        paoCenteiroRadioButton = new javax.swing.JRadioButton();
        paoGengelinRadioButton = new javax.swing.JRadioButton();
        carneBovinaRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        carneFrangoRadioButton1 = new javax.swing.JRadioButton();
        carneSuinaRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        baconCheckBox = new javax.swing.JCheckBox();
        molhoEspecialCheckBox = new javax.swing.JCheckBox();
        alfaceTomateCheckBox = new javax.swing.JCheckBox();
        milhoCheckBox = new javax.swing.JCheckBox();
        CheddarCheckBox = new javax.swing.JCheckBox();
        TorresmoCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        valorPagarLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFO02\\Desktop\\images.jpg")); // NOI18N
        jLabel1.setText("Lanches LFC");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de Pão");

        PaoIntegralRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoPaobuttonGroup.add(PaoIntegralRadioButton);
        PaoIntegralRadioButton.setSelected(true);
        PaoIntegralRadioButton.setText("Pão integral (R$ 1,00)");
        PaoIntegralRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaoIntegralRadioButtonActionPerformed(evt);
            }
        });

        paoCenteiroRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoPaobuttonGroup.add(paoCenteiroRadioButton);
        paoCenteiroRadioButton.setText("Pão Centeiro(R$ 1,50) ");
        paoCenteiroRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paoCenteiroRadioButtonActionPerformed(evt);
            }
        });

        paoGengelinRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoPaobuttonGroup.add(paoGengelinRadioButton);
        paoGengelinRadioButton.setText("Pão com Gergelim(R$ 2,00) ");
        paoGengelinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paoGengelinRadioButtonActionPerformed(evt);
            }
        });

        carneBovinaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarnebuttonGroup.add(carneBovinaRadioButton);
        carneBovinaRadioButton.setSelected(true);
        carneBovinaRadioButton.setText("Carne Bovina(R$2,30)");
        carneBovinaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneBovinaRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de Carne");

        carneFrangoRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarnebuttonGroup.add(carneFrangoRadioButton1);
        carneFrangoRadioButton1.setText("Carne de Frango(R$2,50)");
        carneFrangoRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneFrangoRadioButton1ActionPerformed(evt);
            }
        });

        carneSuinaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        tipoCarnebuttonGroup.add(carneSuinaRadioButton);
        carneSuinaRadioButton.setText("Carne suína(R$3,00)");
        carneSuinaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneSuinaRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Opcionais");

        baconCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        baconCheckBox.setText("Bacon (R$1,60)");
        baconCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconCheckBoxActionPerformed(evt);
            }
        });

        molhoEspecialCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        molhoEspecialCheckBox.setText("Molho especial (R$0,70)");
        molhoEspecialCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                molhoEspecialCheckBoxActionPerformed(evt);
            }
        });

        alfaceTomateCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        alfaceTomateCheckBox.setText("Alface e Tomate (R$0,30)");
        alfaceTomateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfaceTomateCheckBoxActionPerformed(evt);
            }
        });

        milhoCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        milhoCheckBox.setText("Milho(R$0,25)");
        milhoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milhoCheckBoxActionPerformed(evt);
            }
        });

        CheddarCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        CheddarCheckBox.setText("Cheddar(R$2,00)");
        CheddarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheddarCheckBoxActionPerformed(evt);
            }
        });

        TorresmoCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        TorresmoCheckBox.setText("Torresmo(R$0,45)");
        TorresmoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorresmoCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jLabel5.setText("Valor a pagar:");

        valorPagarLabel.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        valorPagarLabel.setForeground(new java.awt.Color(0, 153, 0));
        valorPagarLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valorPagarLabel.setText("R$ 3,30");

        jButton1.setText("Novo Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PaoIntegralRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(baconCheckBox)
                                            .addComponent(molhoEspecialCheckBox)
                                            .addComponent(alfaceTomateCheckBox))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TorresmoCheckBox)
                                                    .addComponent(CheddarCheckBox)
                                                    .addComponent(milhoCheckBox))
                                                .addGap(45, 45, 45))
                                            .addComponent(valorPagarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paoGengelinRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paoCenteiroRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carneSuinaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carneBovinaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carneFrangoRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaoIntegralRadioButton)
                    .addComponent(carneBovinaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paoCenteiroRadioButton)
                    .addComponent(carneFrangoRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paoGengelinRadioButton)
                    .addComponent(carneSuinaRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baconCheckBox)
                    .addComponent(milhoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(molhoEspecialCheckBox)
                    .addComponent(CheddarCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alfaceTomateCheckBox)
                    .addComponent(TorresmoCheckBox))
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorPagarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFO02\\Desktop\\sair.png")); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja sair ?", "Sair",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        carneBovinaRadioButton.setSelected(true);
        PaoIntegralRadioButton.setSelected(true);
        baconCheckBox.setSelected(false);
        milhoCheckBox.setSelected(false);
        molhoEspecialCheckBox.setSelected(false);
        CheddarCheckBox.setSelected(false);
        alfaceTomateCheckBox.setSelected(false);
        TorresmoCheckBox.setSelected(false);
        valorPagarLabel.setText("R$ 3,30");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carneFrangoRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneFrangoRadioButton1ActionPerformed
        calcularValorSanduiche();
    }//GEN-LAST:event_carneFrangoRadioButton1ActionPerformed

    private void PaoIntegralRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaoIntegralRadioButtonActionPerformed
        calcularValorSanduiche();
    }//GEN-LAST:event_PaoIntegralRadioButtonActionPerformed

    private void paoCenteiroRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paoCenteiroRadioButtonActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_paoCenteiroRadioButtonActionPerformed

    private void carneBovinaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneBovinaRadioButtonActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_carneBovinaRadioButtonActionPerformed

    private void paoGengelinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paoGengelinRadioButtonActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_paoGengelinRadioButtonActionPerformed

    private void carneSuinaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneSuinaRadioButtonActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_carneSuinaRadioButtonActionPerformed

    private void baconCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconCheckBoxActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_baconCheckBoxActionPerformed

    private void milhoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milhoCheckBoxActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_milhoCheckBoxActionPerformed

    private void molhoEspecialCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_molhoEspecialCheckBoxActionPerformed
        calcularValorSanduiche();       
    }//GEN-LAST:event_molhoEspecialCheckBoxActionPerformed

    private void CheddarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheddarCheckBoxActionPerformed
        calcularValorSanduiche();        
    }//GEN-LAST:event_CheddarCheckBoxActionPerformed

    private void alfaceTomateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfaceTomateCheckBoxActionPerformed
        calcularValorSanduiche();   
    }//GEN-LAST:event_alfaceTomateCheckBoxActionPerformed

    private void TorresmoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorresmoCheckBoxActionPerformed
        calcularValorSanduiche();
    }//GEN-LAST:event_TorresmoCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaIniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaIniciar().setVisible(true);
            }
        });
    }

    public void calcularValorSanduiche() {
        //formatando
        DecimalFormat formato = new DecimalFormat("R$ #,##0.00");
        //variaveis
        double tipoPao = 0;
        double tipoCarne = 0;
        double valorPagar = 0;
        double opcionais = 0;
        String valorTotalFormatado;
        // verificando tipo de pao 
        if (PaoIntegralRadioButton.isSelected()) {
            tipoPao = 1;
        }
        if (paoCenteiroRadioButton.isSelected()) {
            tipoPao = 1.50;
        }
        if (paoGengelinRadioButton.isSelected()) {
            tipoPao = 2;
        }


        //verificando tipo de carne
        if (carneBovinaRadioButton.isSelected()) {
            tipoCarne = 2.30;
        }
        if (carneFrangoRadioButton1.isSelected()) {
            tipoCarne = 2.50;
        }
        if (carneSuinaRadioButton.isSelected()) {
            tipoCarne = 3;
        }


        //verificando opicionais
        if (baconCheckBox.isSelected()) {
            opcionais += 1.60;
        }
        if (milhoCheckBox.isSelected()) {
            opcionais += 0.25;
        }
        if (molhoEspecialCheckBox.isSelected()) {
            opcionais += 0.70;
        }
        if (alfaceTomateCheckBox.isSelected()) {
            opcionais += 0.30;
        }
        if (CheddarCheckBox.isSelected()) {
            opcionais += 2;
        }
        if (TorresmoCheckBox.isSelected()) {
            opcionais += 0.45;
        }


        valorPagar = tipoCarne + tipoPao + opcionais;

        valorTotalFormatado = formato.format(valorPagar);
        valorPagarLabel.setText(valorTotalFormatado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheddarCheckBox;
    private javax.swing.JRadioButton PaoIntegralRadioButton;
    private javax.swing.JCheckBox TorresmoCheckBox;
    private javax.swing.JCheckBox alfaceTomateCheckBox;
    private javax.swing.JCheckBox baconCheckBox;
    private javax.swing.JRadioButton carneBovinaRadioButton;
    private javax.swing.JRadioButton carneFrangoRadioButton1;
    private javax.swing.JRadioButton carneSuinaRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox milhoCheckBox;
    private javax.swing.JCheckBox molhoEspecialCheckBox;
    private javax.swing.JRadioButton paoCenteiroRadioButton;
    private javax.swing.JRadioButton paoGengelinRadioButton;
    private javax.swing.ButtonGroup tipoCarnebuttonGroup;
    private javax.swing.ButtonGroup tipoPaobuttonGroup;
    private javax.swing.JLabel valorPagarLabel;
    // End of variables declaration//GEN-END:variables
}
